(program 0.0.0
[[[[[[(force (builtin chooseData))
 -- (con data {Integer 2})]
 (con data #02)]
 -- (con data {Constr 1 [Integer 1]})]
 (con data #d87a8101)]
 -- (con data {Map [(Integer 0, ByteString #00), (Integer 1, ByteString #0F)]})]
 (con data #a200410001410f)]
 -- (con data {List [ Integer 0, Integer 1 ]})]
 (con data #820001)]
 -- (con data {Integer 2})]
 (con data #02)]
 -- (con data {ByteString #001A})])
 (con data #42001a)])